### ISSUE TITLE
Allow no action

### ISSUE THREAD

**Issue by demipixel** [twitchinstallsarchlinux/twitch-master#4]
If something is going to take a while to load, download, etc, maybe allow "none" to not do anything? (or some better name)

**Comment by QuiZr** [comment]
+1

**Comment by n17r4m** [comment]
+1 "noop"

**Comment by RX14** [comment]
:+1: for `NOP`

**Comment by xBytez** [comment]
+1 NOP/NOOP will do.

**Comment by XDjackieXD** [comment]
a nop would be good
