### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by Fuyukai** [twitchinstallsarchlinux/twitch-master#7]

**Comment by Thor77** [comment]
such specific

**Comment by LDVSOFT** [comment]
Yep

**Comment by muse** [comment]
Accurate.

**Comment by FruitieX** [comment]
wow

**Comment by ghost** [comment]
so true

**Comment by kailan** [comment]
I can reproduce this issue :+1:

**Comment by luzpaz** [comment]
:+1:

**Comment by ilevn** [comment]
True

**Comment by ImTomEddy** [comment]
needs fixing :+1:

**Comment by alok0** [comment]
stream is frozen, chat bot claims votes are going through but they never show up on console

**Comment by tboHammu** [comment]
Reproducible, doesn't work

**Comment by FrozenDroid** [comment]
shiiiiiit

**Comment by jomo** [comment]
can confirm

**Comment by Admicos** [comment]
could reproduce. needs fixing

**Comment by FrozenDroid** [comment]
confirmed, +1

**Comment by Xe** [comment]
please for fixing

**Comment by oakkitten** [comment]
prs welcome (please one letter per commit)

**Comment by minhoryang** [comment]
+1 It happened to me!

**Comment by phroa** [comment]
The next level would be running a Twitch stream to fix this, commit it, and PR it back.

**Comment by CWood1** [comment]
Stream no longer frozen, commands still don't do anything.

**Comment by summit2g** [comment]
i can confirm

**Comment by pta2002** [comment]
can confirm

**Comment by 69** [comment]
help

**Comment by Fuyukai** [comment]
Resolved.

**Comment by Admicos** [comment]
fixed. needs closing

**Comment by pta2002** [comment]
Bug disapeared

**Comment by jamm0us** [comment]
thank u based sun god

**Comment by walliski** [comment]
Reopen please :D
