### ISSUE TITLE
Something is missing

### ISSUE THREAD

**Issue by mickael9** [twitchinstallsarchlinux/twitch-master#9]
twitch_master.js publishes on `qemu-master` topic while qemu.js listens on `qemu-manager` so this couldn't possibly work unless there's another script to bridge the two, and I guess that would be the one responsible for handling special commands such as `system_reset`.

I don't know if this is missing on purpose, but I'm bringing it in case you just forgot to commit it

**Comment by jbott** [comment]
You are correct. The qemu.js script doesn't work correctly, which was one of the main causes of the initial delay. I am very confused as to how I ever had it working during testing.
